### ISSUE TITLE
Upgrade tensorflow version

### ISSUE THREAD

**Issue by aayushbhaskar** [bedapudi6788/NudeNet#29] opened 2020-01-24 12:06 UTC
Could you please update the model and prediction codes using tensorflow 2.0+, else I'll have to install two different versions of tensorflow for my project.

**Comment by bedapudi6788** [comment] 2020-01-24 12:31
@aayushbhaskar which model? detector or classifier?

**Comment by aayushbhaskar** [comment] 2020-01-24 12:35
The detector model, thanx!

**Comment by bedapudi6788** [comment] 2020-01-24 12:44
@aayushbhaskar have you checked if it works with tf2 and keras 2.3? If yes, can you post the errors?

**Comment by aayushbhaskar** [comment] 2020-01-24 13:01
@bedapudi6788 yeah I've tried, it doesn't work with tf2, because placeholder doesn't exist in tf2.

**Comment by bedapudi6788** [comment] 2020-01-24 13:27
With the latest keras (2.3.1) and tf (2.1.0) versions, there is no way you are getting some placeholder error. The actual error is solved with a simple function renaming.

Just install latest tf, keras packages and change [this](https://github.com/fizyr/keras-retinanet/blob/232166da6ca5ac579e1a1ef9bed0f74f354f7272/keras_retinanet/backend/tensorflow_backend.py#L68) to
```return tensorflow.image.resize(images, size, methods[method])```


The repo has a **bug/issue format** for a reason. It is **good etiquette** to stick to the format since it would have saved me the time to install and check with various versions of multiple libraries.

**Comment by bedapudi6788** [comment] 2020-01-24 13:30
With the latest keras (2.3.1) and tf (2.1.0) versions, there is no way you are getting some placeholder error. The actual error is solved with a simple function renaming.

Just install latest tf, keras packages and change this to
return tensorflow.image.resize(images, size, methods[method])

PS: When creating a new issue for any repo, try to follow the format/template if specified. It would save the devs a lot of time and might actually help you get the solution faster.

**Comment by bedapudi6788** [comment] 2020-01-24 13:51
@aayushbhaskar I am closing the issue. Please re-open if you encounter any other errors.

**Comment by aayushbhaskar** [comment] 2020-01-24 15:55
Sure, thanx

**Comment by aayushbhaskar** [comment] 2020-01-24 15:58
Hi,
I'm really sorry for not following the standard issue format of the repo,
and will pay attention from now on. Thanks again!
Regards.

**Comment by aayushbhaskar** [comment] 2020-01-27 10:02
Hi,
I've installed the nudenet with the command: pip3 install git+https://github.com/bedapudi6788/NudeNet.
I already have the latest tensorflow and keras installed on my system. When I try to create an instance of the detector or classifier the following error occurs:
det = NudeDetector()
Downloading the checkpoint to /root/.NudeNet/detector
MB100% (213.0 of 213.0) |################| Elapsed Time: 0:01:16 Time:  0:01:16
Succefully Downloaded to: /root/.NudeNet/detector
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aayushbhaskar/tfenv/lib/python3.6/site-packages/nudenet/detector.py", line 39, in __init__
    Detector.detection_model = models.load_model(model_path, backbone_name='resnet101')
  File "/home/aayushbhaskar/tfenv/lib/python3.6/site-packages/keras_retinanet/models/__init__.py", line 83, in load_model
    return keras.models.load_model(filepath, custom_objects=backbone(backbone_name).custom_objects)
  File "/home/aayushbhaskar/tfenv/lib/python3.6/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/home/aayushbhaskar/tfenv/lib/python3.6/site-packages/keras/engine/saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/aayushbhaskar/tfenv/lib/python3.6/site-packages/keras/engine/saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/aayushbhaskar/tfenv/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/aayushbhaskar/tfenv/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/aayushbhaskar/tfenv/lib/python3.6/site-packages/keras/engine/network.py", line 1022, in from_config
    process_layer(layer_data)
  File "/home/aayushbhaskar/tfenv/lib/python3.6/site-packages/keras/engine/network.py", line 1008, in process_layer
    custom_objects=custom_objects)
  File "/home/aayushbhaskar/tfenv/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/aayushbhaskar/tfenv/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 147, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "/home/aayushbhaskar/tfenv/lib/python3.6/site-packages/keras/engine/base_layer.py", line 1109, in from_config
    return cls(**config)
  File "/home/aayushbhaskar/tfenv/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/aayushbhaskar/tfenv/lib/python3.6/site-packages/keras/engine/input_layer.py", line 87, in __init__
    name=self.name)
  File "/home/aayushbhaskar/tfenv/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 517, in placeholder
    x = tf.placeholder(dtype, shape=shape, name=name)
AttributeError: module 'tensorflow' has no attribute 'placeholder'

How do I resolve this.

**Comment by bedapudi6788** [comment] 2020-01-27 15:08
Are you sure you installed keras and tensorflow latest versions on python
3.6 (post the pip show outputs for them if possible)? Can you reproduce the
issue on a colab if possible?

**Comment by bedapudi6788** [comment] 2020-01-27 15:09
Oh, I just realised that you deleted the comment I replied to. Hope you were able to get it working. Please re-open if you still encounter any errors.

**Closed by bedapudi6788** 2020-01-27 15:09 UTC
Labels: enhancement
